language: minimal

os: linux

addons:
    apt:
        packages:
            - texlive-latex-extra
            - dvipng
            - texlive-fonts-recommended

env:
    global:
        - PYTHON_VERSION=3.7
        - ASTROPY_VERSION=stable
        - NUMPY_VERSION=1.18
        - CONDA_DEPENDENCIES='scipy scikit-learn matplotlib'
        - PIP_DEPENDENCIES='pytest-doctestplus>=0.3 pytest-remotedata pytest-astropy-header'
        - PIP_ALL_DEPENDENCIES='scipy scikit-learn matplotlib pytest-astropy'
        - DEBUG=True
        - SCRIPT_CMD='pytest astroML'

matrix:
    fast_finish: true

    include:
        - env: NUMPY_VERSION=1.17 SCRIPT_CMD='pytest astroML --remote-data'

        - env: NUMPY_VERSION=1.16

        - env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.14

        - env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.13

        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.12 ASTROPY_VERSION=3.0 PIP_DEPENDENCIES='scipy==1.0.* scikit-learn matplotlib pytest-astropy'
               CONDA_DEPENDENCIES='' PYTEST_VERSION=">4"

        - env: PYTHON_VERSION=3.6 SCRIPT_CMD='make -C doc html' PIP_DEPENDENCIES='sphinx'

        - env: PYTHON_VERSION=3.8 PIP_DEPENDENCIES=$PIP_ALL_DEPENDENCIES
               CONDA_DEPENDENCIES=""

   allow_failures:
        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.12 ASTROPY_VERSION=3.0 PIP_DEPENDENCIES='scipy==1.0.* scikit-learn matplotlib pytest-astropy'
               CONDA_DEPENDENCIES='' PYTEST_VERSION=">4"

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py install

script:
    - $SCRIPT_CMD
