language: generic

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

os: linux

# The apt packages below are needed for sphinx builds. A full list of
# packages that can be included can be found here:
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
    apt:
        packages:
            - gfortran

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSON=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='scipy scikit-learn<0.19 nose matplotlib pymc'
        - PIP_DEPENDENCIES='astroML_addons'
        - DEBUG=true

matrix:
    fast_finish: true

    include:
        - env: PYTHON_VERSION=3.7

        - env: NUMPY_VERSION=1.14

        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.13

        - env: PYTHON_VERSION=3.4

        - env: PYTHON_VERSION=2.7


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - python setup.py install

script:
    - nosetests astroML
