name: CI

on:
  push:
    branches:
    - master
    - gitActionsTest
    tags:
    - '*'
  pull_request:
    branches:
    - master
  schedule:
    # run every Monday at 5am UTC
    - cron: '0 5 * * 1'

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:

          - name: Code style checks
            os: ubuntu-latest
            python: 3.x
            toxenv: codestyle

          - name: docs build
            os: ubuntu-latest
            python: 3.8
            toxenv: build_docs
            toxargs: -v

          #- name: oldest dependencies
          #  os: ubuntu-latest
          #  python: 3.6
          #  toxenv: py36-test-oldestdeps
          #  toxargs: -v

          - name: astropy dev with all dependencies with coverage
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test-devastropy-cov
            toxargs: -v

          - name: Python 3.7 with all optional dependencies (MacOS X)
            os: macos-latest
            python: 3.7
            toxenv: py37-test
            toxargs: -v

          - name: Python 3.8 with mandatory dependencies (Windows)
            os: windows-latest
            python: 3.8
            toxenv: py38-test
            toxargs: -v

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
    - name: Upload coverage to codecov
      if: contains(matrix.toxenv,'-cov')
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml

  # This needs to be outside of matrix because if is not supported
  # for only one job in a matrix. But once that is supported, this can go
  # back to the matrix above.
  remote_data:
    name: Python 3.8 with all dependencies with remote data
    if: github.event_name == 'schedule' && github.repository == 'astropy/astroquery'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox -v -e py38-test-alldeps-devastropy -- --remote-data

  egg_info:
    name: egg_info with Python 3.7
    runs-on: ubuntu-latest
    needs: cancel_ci
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Run egg_info
      run: python setup.py egg_info
